### ISSUE TITLE
Faltando script develop_server.sh

### ISSUE THREAD

**Issue by eliasdorneles** [grupydf/grupybr-template#3]
Estamos testando o template, mas quando tentamos usar `make devserver`, dá erro porque não tem o script develop_server.sh -- alguém esqueceu de comitar? :)

```
$ make devserver
/home/elias/src/grupybr-template/develop_server.sh restart
make: /home/elias/src/grupybr-template/develop_server.sh: Command not found
make: *** [devserver] Error 127
```

**Comment by magnunleno** [comment]
Devo ter esquecido, já estou corrigindo. Obrigado!
